command:
  - uvicorn
  - main:app
  - --host
  - 0.0.0.0
  - --port
  - 8000

env:
  - name: CATALOG
    value: "catalog_control_gyw546"
  - name: DATABRICKS_HOST
    value: "https://adb-7405607353957441.1.azuredatabricks.net"
  - name: LAKEBASE_PROJECT_ID
    value: "mission-control"
  - name: LAKEBASE_BRANCH_ID
    value: "production"
  - name: WAREHOUSE_ID
    value: "dfa2d4c7b330f867"
  - name: SIMULATION_JOB_ID
    value: "89935679578653"
  - name: RETRAIN_JOB_ID
    value: "1079020504092201"
